doc: update documentation on release
nrfconnect/sdk-sidewalk pull request #348
Opened 2023-06-02 08:21 UTC by ktaborowski

[KRKNWK-17045]

2023-06-02 08:22 UTC, ktaborowski commented on doc/sidewalk_release_notes.rst
> +[v1.14.4] - 06/XX/2023
'XX' will be changed on release date when knwon

2023-06-05 06:31 UTC, annwoj requested changes

2023-06-05 06:31 UTC, annwoj commented on doc/sidewalk_release_notes.rst
> +* Rleased Sidewalk based on the nRF Connect SDK v2.4.0.
```suggestion
* Released Sidewalk based on the nRF Connect SDK v2.4.0.
```

2023-06-05 06:31 UTC, annwoj commented on doc/sidewalk_release_notes.rst
> +* Moved Semtech pins configuration to DTS.
```suggestion
* Moved the Semtech pins configuration to DTS.
```

2023-06-05 06:31 UTC, annwoj commented on doc/sidewalk_release_notes.rst
> +* Changed DFU mode bahvaiour. Device restes before enter the mode.
```suggestion
* Changed the DFU mode behavior. 
  The device now resets before entering the DFU mode.
```

2023-06-05 06:31 UTC, annwoj commented on doc/sidewalk_release_notes.rst
> +* Notified DFU state with LEDs.
```suggestion
* Added notifying through LEDs whenever the device enters the DFU mode.
```

Rephrased a bit, please let me know if the meaning is affected

2023-06-05 06:31 UTC, annwoj commented on doc/sidewalk_release_notes.rst
> +* Automated repository maintenace with GitHub Actions.
```suggestion
* Automated the repository maintenance with GitHub Actions.
```

2023-06-05 07:21 UTC, annwoj approved these changes

2023-06-05 07:32 UTC, totyz requested changes

2023-06-05 07:32 UTC, totyz commented on doc/sidewalk_release_notes.rst
> +
```suggestion
* show link status for every transport in serial log
* Add [aws iot core tools](https://github.com/aws-samples/aws-iot-core-for-amazon-sidewalk-sample-app) to the west.yml manifest file
```

2023-06-05 09:21 UTC, ktaborowski commented on doc/sidewalk_release_notes.rst
> +
Done

2023-06-05 09:42 UTC, ktaborowski commented on doc/sidewalk_release_notes.rst
> +* Added aws iot core tools repostiory to the west manifest file.
Link added, thanks for suggestions

2023-06-05 09:51 UTC, totyz approved these changes

2023-06-05 10:08 UTC, merged