Fix release flash
nrfconnect/sdk-sidewalk pull request #432
Opened 2023-10-11 10:58 UTC by ktaborowski

2023-10-11 12:45 UTC, totyz requested changes
nrf52 release version is still failing

2023-10-11 13:24 UTC, ktaborowski commented
> nrf52 release version is still failing

Added overlay for nRF52

2023-10-13 15:15 UTC, ktaborowski commented
Manually tested build, update nrf53 and nrf52, template ble and subghz to simple bootloader apps

2023-10-16 10:16 UTC, totyz approved these changes

2023-10-16 10:27 UTC, merged