doc: included previous known issues
nrfconnect/sdk-sidewalk pull request #451
Opened 2023-11-08 12:41 UTC by annwoj

Added previous known issues per release.
Added toggle extension.

2023-11-09 11:18 UTC, ktaborowski requested changes
Please add dev to v1.14.5 before merge (another comments are just comment)

2023-11-09 11:58 UTC, annwoj commented on doc/sidewalk_release_notes.rst
> +        Currently there is no workaround for this issue.
thanks for checking! removed

2023-11-09 11:59 UTC, annwoj commented on doc/conf.py
corrected

2023-11-10 08:20 UTC, ktaborowski approved these changes
looks good :)

2023-11-10 08:22 UTC, merged