samples: clear pending msg after first send
nrfconnect/sdk-sidewalk pull request #493
Opened 2024-02-14 17:29 UTC by ktaborowski

[KRKNWK-18499]
Fixes assert double free on msg

2024-02-15 12:42 UTC, totyz commented
Stress tests: https://jenkins-ncs.nordicsemi.no/job/KRKNG/job/Sidewalk/job/test-sdk-sidewalk/job/test-branch/100/

2024-02-15 14:16 UTC, totyz requested changes
Issue is still visible.

2024-02-26 08:30 UTC, RobertGalatNordic approved these changes

2024-03-06 12:57 UTC, totyz approved these changes

2024-03-06 14:11 UTC, merged