new provisoing and security documentation
nrfconnect/sdk-sidewalk pull request #601
Opened 2024-09-09 13:01 UTC by ktaborowski

## CI parameters

```yaml
Github_actions:
  #(branch, hash, pull/XXX/head)
  NRF_revision: main

  # Do not change after creating PR
  Create_NRF_PR: false
Jenkins:
  test-sdk-sidewalk: master
```

## Description

JIRA ticket: 

## Self review

- [ ] There is no commented code.
- [ ] There are no TODO/FIXME comments without associated issue ticket.
- [ ] Commits are properly organized.
- [ ] Change has been tested.
- [ ] Tests were updated (if applicable).

2024-09-11 07:18 UTC, totyz requested changes

2024-09-11 07:18 UTC, totyz commented on doc/samples/sid_end_device.rst
> +The storage mechanism is based on the `hardware unique key library<https://docs.nordicsemi.com/bundle/ncs-latest/page/nrf/libraries/security/hw_unique_key.html>`_.
The link is not displayed correctly

2024-09-11 07:18 UTC, totyz commented on doc/releases_and_migration/migration_guide_v280.rst
This page is not visible in built documentation

2024-09-11 07:18 UTC, totyz commented on doc/releases_and_migration/migration_guide_v280.rst
> +The mfg parser module launched on init will writhe the manufacturing data in flash (secure key storage) the same way on device certification module does.
```suggestion
The mfg parser module launched on init will write the manufacturing data in flash (secure key storage) the same way on device certification module does.
```

2024-09-11 07:18 UTC, totyz commented on doc/releases_and_migration/migration_guide_v280.rst
> +The secure key storage is based on `hardware unique key<https://docs.nordicsemi.com/bundle/ncs-latest/page/nrf/libraries/security/hw_unique_key.html#lib-hw-unique-key>`_ security library.
link is not displayed correctly

2024-09-11 08:59 UTC, RobertGalatNordic commented on doc/releases_and_migration/migration_guide_v280.rst
> +This feature is disable is Sidewalk DUT sample to alow writing manufacturing data using on device certification commands.
disable **in** Sidewalk DUT ... 

just a typo

2024-09-12 07:14 UTC, totyz commented
built docs: https://jenkins-ncs.nordicsemi.no/job/KRKNG/job/Sidewalk/job/test-sdk-sidewalk/job/master/1169/artifact/html_doc/index.html

2024-09-12 13:05 UTC, annwoj commented on doc/includes/include_kconfig_common.txt
> +* ``SIDEWALK_MFG_STORAGE_SUPPORT_HEX_v7`` - Enables support for old Sidewalk manufacturing hex format.
Maybe it would be better to indicate the release version instead? "old" sounds very vague

2024-09-12 13:05 UTC, annwoj commented on doc/releases_and_migration/migration_guide_v280.rst
> +Although it is highly recommended to use the new provisioning module implementation, the old one can be enabled using ``CONFIG_DEPRECATED_SIDEWALK_MFG_STORAGE`` configuration.
```suggestion
It is recommended to use the new provisioning module implementation. 
However, you can still enable the old module using the ``CONFIG_DEPRECATED_SIDEWALK_MFG_STORAGE`` Kconfig option. 
```

2024-09-12 14:04 UTC, ktaborowski commented on doc/samples/sid_end_device.rst
> +The Nordic platform supports a secure key storage mechanism for Sidewalk keys, ensuring they are stored persistently and confidentially.
I though about it, and it seems to be the most specufic name for me - it's nota an Amazon protocol library which ansures keys are securealy stored, also it's not any specyfic chip - it's a software solution implemented in Sidewalk's platform abstraction layer for nrf connect sdk

2024-09-13 08:40 UTC, annwoj commented on Kconfig
> +	  it must be enabled in every next build.
```suggestion
	  Once you flash the firmware with this config enabled,
	  it must be enabled in every subsequent build.
```

2024-09-13 08:40 UTC, annwoj commented on Kconfig
> +	  Otherwise the keys will not be found and Sidewalk will not start.
```suggestion
	  Otherwise, the keys will not be found and Sidewalk will not start.
```

2024-09-13 08:40 UTC, annwoj commented on doc/includes/include_kconfig_common.txt
> +* ``SIDEWALK_MFG_STORAGE_SUPPORT_HEX_v7`` - Enables support for Sidewalk manufacturing hex in version 7 and below.
```suggestion
* ``SIDEWALK_MFG_STORAGE_SUPPORT_HEX_v7`` - Enables support for Sidewalk manufacturing HEX in version 7 and below.
```

2024-09-13 08:40 UTC, annwoj commented on doc/releases_and_migration/migration_guide_v280.rst
> +
```suggestion
```

2024-09-13 08:40 UTC, annwoj commented on Kconfig
> +	  and will be supported after enablig this configuration.
```suggestion
	  and will be supported after enabling this configuration.
```

2024-09-13 08:40 UTC, annwoj commented on doc/releases_and_migration/migration_guide_v280.rst
> +
Just thought of it now, but maybe this (L22-41) could be a separate section called, e.g., "Implementation details", or a bit more precise: "Security enhancements details"? "Reasons for change" seem to end with the above bullet points

```suggestion

Security enhancements details
=============================
```

2024-09-13 09:10 UTC, annwoj approved these changes

2024-09-13 09:23 UTC, totyz approved these changes

2024-09-13 09:31 UTC, merged